# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCcXPuEb0B963_e3nqRVGpajQUy71N5a
"""

# Install dependencies as needed:
!pip install kagglehub
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "creditcard_2023.csv"  # Changed to a valid CSV file name within the dataset

# Load the latest version
df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "nelgiriyewithana/credit-card-fraud-detection-dataset-2023",
    file_path,
    # Provide any additional arguments like
    # sql_query or pandas_kwargs. See the
    # documenation for more information:
    # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

kmeans = KMeans()
kmeans.fit(df_scaled)

plt.figure(figsize=(10, 5))
sns.scatterplot(x=df['V1'], y=df['V2'], hue=df['Class'],palette='Set2',s=100)
plt.title('Clusters of Customers')
plt.xlabel('Age')
plt.ylabel('Spending Score')
plt.show()
